// Turns src/assets/*.jpg|png into an ES module of data URIs.
//
// The headline of this build is "open dist/terrarium.html — one file, no
// server, no network". A background loaded by URL breaks that three ways: it
// is a second request, it fails under file://, and esbuild's IIFE bundle has
// no `import.meta.url` to resolve it against. Embedding sidesteps all three
// and leaves exactly one code path for dev, bundle and deploy.
//
// Run via `npm run build`. The .jpg stays the source of truth; the .js is
// generated and should never be hand-edited.

import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { dirname, resolve, extname, basename } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const dir = resolve(root, 'src/assets');

const MIME = { '.jpg': 'image/jpeg', '.jpeg': 'image/jpeg', '.png': 'image/png' };

for (const file of readdirSync(dir)) {
  const ext = extname(file).toLowerCase();
  const mime = MIME[ext];
  if (!mime) continue;

  const name = basename(file, ext);
  const bytes = readFileSync(resolve(dir, file));
  const uri = `data:${mime};base64,${bytes.toString('base64')}`;

  writeFileSync(resolve(dir, `${name}.js`),
    `// GENERATED by tools/embed-assets.mjs from ${file} — do not edit.\n` +
    `// ${(bytes.length / 1024).toFixed(0)} KB source, inlined so the single-file\n` +
    `// build stays a single file with no network.\n` +
    `export const ${name.toUpperCase()}_URI =\n  '${uri}';\n` +
    `export default ${name.toUpperCase()}_URI;\n`);

  console.log(`embedded ${file} -> src/assets/${name}.js (${(uri.length / 1024).toFixed(0)} KB)`);
}
